apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: eventer
    task: monitoring
  name: kube-eventer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: eventer
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      labels:
        k8s-app: eventer
        task: monitoring
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: k8s.aliyun.com
                    operator: NotIn
                    values:
                      - 'true'
      containers:
        - command:
            - /kube-eventer
            - '--source=kubernetes:https://kubernetes.default'
            - >-
              --sink=sls:https://sls.aliyuncs.com?project=<sls_project>&logStore=<sls_logstore>>&topic=<topic_name>
          image: >-
            registry.aliyuncs.com/acs/kube-eventer:v1.2.7-ca03be0-aliyun
          imagePullPolicy: IfNotPresent
          name: eventer
          resources: {}
          env:
            - AccessKeyId: "xxx"
            - AccessKeySecret: "xxx"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: ack-node-problem-detector
      serviceAccountName: ack-node-problem-detector
